### ISSUE TITLE
Add results from survey

### ISSUE THREAD

**Issue by dhimmel** [asapbio/licensing#1]
I created the first two commits to get this repo started: 546af74dc439668b77c3aaa31ccbc6ab80bd7f7d and b8aba56945e8048bee8140951220aeb4d90188c1. From now on, I'll switch to committing to a fork and submitting pull requests.

If we only want CC0 to apply to a subset of this repo, we should address that now. I'm fine with it applying to everything including our code, figures, and documentation.

@jpolka do you want to upload the raw data from the survey? Perhaps, in a `data` directory? The unmodified format straight from Google Forms would be best. Also you could add a modified version... not sure if you had to do any manual cleaning.

git and GitHub can be quite confusion. Not sure how familiar you are with it. For another project, we have some documentation on the collaborative workflow [here](https://github.com/cognoma/cognoma/blob/master/CONTRIBUTING.md#contribution-workflow). Happy to walk anyone through the process if they're having trouble contributing here.

**Comment by jpolka** [comment]
Fine with leaving this CC0!  Raw survey responses and ppt & xls files added.
